# Generated by Django 4.2.7 on 2023-11-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_order_date_order_description_order_store_order_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('post', 'پست'), ('tipax', 'تیپاکس'), ('delivery', 'پیک موتوری')], max_length=20, null=True),
        ),
    ]
