# Generated by Django 4.2.7 on 2023-11-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_remove_order_description_order_document_defects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
