# Generated by Django 4.2.7 on 2023-12-10 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_order_description_order_time_alter_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=20)),
                ('fa_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Shipping Method',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.shippingmethod'),
        ),
    ]
