# Generated by Django 4.2.7 on 2023-12-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_remove_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
